FROM tensorflow/tensorflow:1.15.0-gpu-py3-jupyter

ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

RUN pip install --upgrade pip
RUN pip install tensor2tensor
RUN pip install tokenizer

WORKDIR /tensorflow
